version: '3.7'
services:

  # Splunk
  splunk:
    image: splunk/splunk:latest
    deploy:
      resources:
        limits:
          cpus: '1'
    hostname: splunk
    ports:
      - "8000:8000"
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "ch@ngeM3"
    volumes:
      - ./TA-config:/opt/splunk/etc/apps/TA-config
      - ./01-source-CIM:/tmp/01-source-CIM
      - ./01-source-CIM/Splunk_SA_CIM:/opt/splunk/etc/apps/Splunk_SA_CIM
      - ./02-target-CIM:/tmp/02-target-CIM      
      - ./03-control-dashboard/datamodel_comparator.xml:/opt/splunk/etc/apps/search/local/data/ui/views/datamodel_comparator.xml
      - ./04-out-package:/tmp/04-out-package      
